version: '3'

services:
  app:
    build: app
    ports:
      - "8080:8080"
    environment:
      GUNICORN_DIR: /app
      LOGLEVEL: INFO
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8009:80
    links:
      - app
